Add vim7.3 compatibility
VimCompletesMe uses the CompleteDone autocmd event along with the
InsertLeave autocmd event to control the behavior of context switch you
get from pressing Tab again when there are no completion items available
with the current completion type.

However, the CompleteDone event was introduced in vim 7.3, patch number
598. This commit fixes the issue where Vim would output the following
error: 'E216: No such group or event: CompleteDone'.

This does mean that VimCompletesMe's context switch after completing
while staying in Insert mode will not be available to users that use
a Vim version less than  vim7.3.589. This commit does not affect Vim7.4.
A workaround is to go to Normal mode after completing, if users need the
context switch ability for the next completion.

References #9